version: "3"

services:

  springdb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mesghal
      MYSQL_USER: user
      MYSQL_PASSWORD: secretpass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  springapp:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - springdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://springdb:3306/mesghal?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: springdb
      DB_DATABASE: mesghal
      DB_USER: user
      DB_PASSWORD: secretpass
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    #      JDBC_PARAMS: "useSSl=false"
    ports:
      - 8080:8080
    depends_on:
      - springdb

volumes:
  db_data:
